export const bbnEmployees = [
  "Bored Thien",
  "Zerena",
  "NewFall",
  "Stella",
  "Alexandre Vachon",
  "BlasterTNT",
  "Catnovem",
  "IQF",
  "Freddie Fazbear",
  "Math Goblin",
  "NilGaming",
  "Sami9999999999",
  "Akui No Chuushin",
  "Daniel R.",
  "Gamma Mu D Mu",
  "Horizontia",
  "HyperNumbersAnimation",
  "Istamtae",
  "JoshuaDR.0809",
  "Kaifinity",
  "Kittenbike",
  "TneEnchantedPokemon",
  "Psifinity",
  "SuperWindows78",
  "Outspace Gigane"
].sort();