export const bbnEmployees = [
  "Bored Thien",
  "Zerena",
  "NewFall",
  "Stella",
  "Blast100",
  "Catnovem",
  "IQF",
  "Math Goblin",
  "NilGaming",
  "Sami9999999999",
  "Akui No Chuushin",
  "Daniel R.",
  "Gamma Mu D Mu",
  "Horizontia",
  "HyperNumbersAnimation",
  "Istamtae",
  "JoshuaDR.0809",
  "Kaifinity",
  "Kittenbike",
  "TneEnchantedPokemon",
  "Psifinity",
  "SuperWindows78",
  "Outspace Gigane",
  "CurliestJohn",
  "Oscar Wood",
  "Pixelium",
  "Aperdinal",
  "TCC25",
].sort();

export const councilMembers = [
  "Math Goblin",
  "Gamma Mu D Mu",
  "Bored Thien",
  "Zerena",
].sort();
