export const bbnEmployees = [
  "Skylafalls",
  "Zerena",
  "NewFall",
  "Stella",
  "Blast100",
  "Catnovem",
  "IQF",
  "Math Goblin",
  "NilGaming",
  "Sami9999999999",
  "Akui No Chuushin",
  "Daniel R.",
  "Gamma Mu D Mu",
  "Myria",
  "HyperNumbersAnimation",
  "Istamtae",
  "JoshuaDR.0809",
  "Kaifinity",
  "Kittenbike",
  "TneEnchantedPokemon",
  "Psifinity",
  "SuperWindows78",
  "Outspace Gigane",
  "CurliestJohn",
  "Oscar Wood",
  "Pixelium",
  "Aperdinal",
  "TCC25",
  "Elaborant500",
  "Spelpotatis",
  "Static",
  "StrongLeon",
  "DrBruntToast",
  "Eriana",
  "Landon25",
].toSorted();

export const councilMembers = [
  "Math Goblin",
  "Gamma Mu D Mu",
  "Skylafalls",
  "Zerena",
].toSorted();
